spring:
  application:
    name: project_cal
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://138.2.119.233:3306/project01
    username: project01
    password: 7e0f51dbca86c4d8f8bdc38bd3503b883f84e3fb120d93f6aeaf885033c4a6f4
  #멀티파트를 위한 설정
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 200MB
        location: c:\\uploads
  #스프링 시큐리티 설정
  security:
    user:
      name: user
      password: 1234
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/, classpath:/resources/, classpath:/META-INF/resources/, file:src/main/webapp/
#이메일 토큰
  oauth2:
    client:
      registration:
        naver:
          client-id: fCbESEtEsGr2Lcs5w2Lp3
          client-secret: vS1egkAK42
          redirect-uri: "http://localhost:8080/project_cal/login/oauth2/code/naver"
          authorization-grant-type: authorization_code
          scope: profile,email
          client-name: Naver
  provider:
    naver:
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    user-name-attribute: response.email
mail:
  host: smtp.naver.com
  port: 587
  username: himj9515
  userpassword: himedia9515
  properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
  connectiontimeout: 5000
  timeout: 5000
  writetimeout: 5000
server:
  servlet:
    session:
      cookie:
        name: PROJECTCAL_SESSIONID
      timeout: 20m # 세션 유효 시간 설정
# 파일 경로 바꾸려면 util 클래스의 FilesUtility에서 확인
file:
  upload-dir: /uploads
#디버깅
  logging:
    level:
    root: DEBUG

upload-dir: /uploads



